apiVersion: v1
version: 3.0.1
appVersion: 8.6.4
description: One of the most versatile open source content management systems.
name: drupal
keywords:
- drupal
- cms
- blog
- http
- web
- application
- php
home: http://www.drupal.org/
icon: https://bitnami.com/assets/stacks/drupal/img/drupal-stack-220x234.png
maintainers:
- name: Nilesh
  email: nilesh.a.kanawade@gmail.com
engine: gotpl
